# Generated by Django 3.2.8 on 2021-10-21 02:46

import csv

from django.db import migrations, models


def load_pets_from_csv(apps, schema_editor):
    Pet = apps.get_model('web', 'Pet')
    db_alias = schema_editor.connection.alias

    with open("./pets.csv") as f:
        reader = csv.reader(f)
        # Skip header row
        next(reader)
        for row in reader:
            species = row[0]
            name = row[1]
            age = int(row[2])
            _, created = Pet.objects.using(db_alias).get_or_create(
                species=species,
                name=name,
                age=age,
            )
            if created:
                print(f"Created Pet {name} {species} {age}")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RunPython(load_pets_from_csv)
    ]
